// priority: 150
// 攻击， 生命， 护甲
/**
 * 生物对应的模板
 */
const mobTypes = {
    "thermal_shock:willograde": typeD,
    "thermal_shock:trilobite": typeB,
    "thermal_shock:graver": typeA,
    "thermal_shock:skullscor": typeB,
    "thermal_shock:skeletitan": typeC,
    "thermal_shock:mantletitan": typeD,
    "thermal_shock:frost_titan": typeD,
    "thermal_shock:errant": typeB,
    "thermal_shock:gore_flayer": typeB,
    "thermal_shock:magnetite": typeD,
    "thermal_shock:bonerahna": type0,
    "thermal_shock:frostilyte": typeA,
    "thermal_shock:frostilyte_soldier": typeA,
    "thermal_shock:icidrone": typeB,
    "thermal_shock:icidrogrunt": typeB,
    "thermal_shock:icidrozerk": typeC,
    "thermal_shock:galvanite": typeA,
    "thermal_shock:infestophage_seed": type0,
    "thermal_shock:dormant_monolith": typeC,

    "thermal_shock:amalgel": bossType1,
    "thermal_shock:icidroburner": bossType1,
    "thermal_shock:icidrogunner": bossType1,

    "minecraft:zombie": typeA,
    "minecraft:skeleton": typeA,
    "minecraft:spider": typeB,
    "minecraft:creeper": typeB,

    "twilightforest:towerwood_borer": typeB,
    "twilightforest:carminite_broodling": typeB,
    "twilightforest:fire_beetle": typeA,
    "twilightforest:slime_beetle": typeC,
    "twilightforest:pinch_beetle": typeA,
    "twilightforest:blockchain_goblin": typeA,
    "twilightforest:lower_goblin_knight": typeD,
    "twilightforest:skeleton_druid": typeB,
    "twilightforest:redcap_sapper": typeA,
    "twilightforest:redcap": typeA,
    "twilightforest:pinch_beetle": typeB,
    "twilightforest:kobold": typeA,
    "twilightforest:king_spider": bossType1,
    "twilightforest:hostile_wolf": typeB,
    "twilightforest:helmet_crab": typeB,
    "twilightforest:hedge_spider": typeB,
    "twilightforest:death_tome": typeA,
    "twilightforest:wraith": typeA,
    "twilightforest:swarm_spider": typeB,
    "twilightforest:mist_wolf": typeB,

    "twilightforest:minotaur": typeAEX2,
    "twilightforest:maze_slime": typeSlime,
    "twilightforest:carminite_golem": typeCEX2,
    "twilightforest:carminite_ghastling": typeB,
    "twilightforest:carminite_ghastguard": typeB,
    "twilightforest:stable_ice_core": typeAEX2,
    "twilightforest:snow_guardian": typeAEX2,
    "twilightforest:ice_crystal": typeB,
    "twilightforest:giant_miner": typeCEX2,
    "twilightforest:armored_giant": typeCEX2,
    "twilightforest:yeti": typeAEX2,
    "twilightforest:winter_wolf": typeB,
    "twilightforest:unstable_ice_core": typeB,
    "twilightforest:troll": typeAEX2,
    "twilightforest:adherent": typeAEX2,
    "twilightforest:harbinger_cube": typeCEX2,

    "twilightforest:naga": bossType1,
    "twilightforest:lich": bossType2,
    "twilightforest:knight_phantom": bossType1,
    "twilightforest:ur_ghast": bossType1,
    "twilightforest:minoshroom": bossType1EX1,
    "twilightforest:hydra": bossType2EX2,
    "twilightforest:alpha_yeti": bossType2EX2,
    "twilightforest:snow_queen": bossType2EX2,

    "ad_astra:star_crawler": typeA,
    "ad_astra:corrupted_lunarian": typeC,

    "aether:aechor_plant": typeB,
    "aether:blue_swet": typeSlime,
    "aether:cockatrice": typeB,
    "aether:fire_minion": typeD,
    "aether:golden_swet": typeSlime,
    "aether:mimic": typeA,
    "aether:sentry": typeD,
    "aether:valkyrie": typeC,
    "aether:zephyr": typeC,
    "deep_aether:venomite": typeB,
    "aether_redux:vanilla_swet": typeSlime,

    "aether:valkyrie_queen": bossType1,
    "aether:slider": bossType2,
    "aether:sun_spirit": bossType2,
    "aether:valkyrie_queen": bossType1,
    "lost_aether_content:aerwhale_king": bossType2,
    "deep_aether:eots_segment": bossType1,
    "deep_aether:eots_controller": bossType2,

};
/**
 * 黑名单
 */
const entityBlackList = new Set([
    "powerful_dummy:test_dummy",
    "terra_entity:summon_diamond_sword",
    "terra_entity:summon_golden_sword",
    "terra_entity:summon_imp",
    "terra_entity:summon_iron_sword",
    "terra_entity:summon_netherite_sword",
    "terra_entity:summon_snow_flinx",
    "terra_entity:summon_stone_sword",
    "terra_entity:summon_wooden_sword"
]);
