#Advanced settings for performance and stability.
performance_tuning = {}

#General settings for the mod.
[general]
	#Enable or disable the mod entirely.
	enabled = true
<<<<<<< HEAD
	#Show a warning when using the mod in singleplayer.
	singleplayer-warning = true
	#Enable automatic update checks.
	automatic-updater = true

#Enable or disable specific acceleration features.
[acceleration_modules]
	block_entity = false
=======
>>>>>>> 3f220ae98388356c5b7b87c14b77621f976e1bac

